{{- $ctx := .Values }}
#FORMAT:TERRAFORM
00_setting.tf: |
  terraform {
    backend "gcs" {
      bucket  = "{{ .Values.config.stateBucket }}"

      {{- if not (hasKey .Values.config "bucketPrefix") }}
      prefix = "tf-{{ .Values.config.project }}-gcp"
      {{- else if eq .Values.config.bucketPrefix "" }}
      prefix = "tf-{{ .Values.config.project }}-gcp"
      {{- else }}
      prefix = "{{ .Values.config.bucketPrefix }}"
      {{- end }}
    } 
    
    required_providers {      
      {{- range $key, $provider := $ctx.providers }}

      {{- if eq $key "google" }}
      google = "{{ $provider.version }}"
      {{- end }}

      {{- if eq $key "rke" }}
      rke = {
        version = "{{ $provider.version }}"
        source = "{{ $provider.source }}"
      }
      {{- end }}

      {{- end }}
    }
  }

  {{- range $key, $provider := $ctx.providers }}
  {{- if eq $key "google" }}
  provider "google" {  
    project     = "{{ $provider.project }}"
    region      = "{{ $provider.region }}"
  }
  {{- end }}

  {{- if eq $key "rke" }}
  provider "rke" {
    log_file = "{{ $provider.logFile }}"
  }
  {{- end }}
  {{- end }}

